version: "3.8"

services:
  db:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: jihane
      POSTGRES_USER: dbuser
      POSTGRES_DB: NetStream 
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgres/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  pg-admin:
    image: dpage/pgadmin4:6
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - "5050:5050"

volumes:
  pg_data: